USE [master]
GO

/****** Object:  Database [PrsDb]    Script Date: 9/2/2019 9:17:51 PM ******/
CREATE DATABASE [PrsDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PrsDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PrsDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PrsDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PrsDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PrsDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PrsDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PrsDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PrsDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PrsDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PrsDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [PrsDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PrsDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PrsDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PrsDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PrsDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PrsDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PrsDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PrsDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PrsDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PrsDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PrsDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PrsDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PrsDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PrsDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PrsDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PrsDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PrsDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PrsDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PrsDb] SET  MULTI_USER 
GO

ALTER DATABASE [PrsDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PrsDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PrsDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PrsDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PrsDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PrsDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PrsDb] SET  READ_WRITE 
GO


